#!/bin/bash 
#PBS -N mapgd-origin-proview
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=100:00:00
#PBS -l vmem=100gb
#PBS -M ouqd@hotmail.com
#PBS -m abe
#PBS -j oe

set +x
echo PBS -N mapgd-origin-proview
echo PBS -k o
echo PBS -l nodes=1:ppn=16,walltime=12:00:00
echo PBS -l vmem=100gb
echo PBS -M ouqd@hotmail.com
echo PBS -m abe
echo PBS -j oe
echo Updated on 05/28/2018
echo module rm gcc
echo module load gcc
echo module load gsl
echo module load samtools
module rm gcc
module load gcc
module load gsl  
module load samtools

echo SampleID=PA2013
echo DATA_DIR=/N/dc2/scratch/xw63/$SampleID/Bwa
echo HeaderFile=/N/dc2/scratch/xw63/$SampleID/PA42.header

set -x
cd $DATA_DIR
set +x
echo ===============================================================
echo 0. Make a header file
echo ===============================================================
set -x
echo samtools view -H $DATA_DIR/$SampleID-001-RG_Sorted_dedup_realigned_Clipped.bam > $HeaderFile
set +x
echo ===============================================================
echo 1. Make a pro file of nucleotide-read quartets -counts of A, C, G, and T, from the mpileup files of the clones.
echo ===============================================================
set -x
time mapgd proview -i *.mpileup -H $HeaderFile > $SampleID.pro.txt
set +x
echo ===============================================================
echo =============Task 1 completed.===================
echo ===============================================================


