#!/bin/bash	
#PBS -N bwa-sampe-003
#PBS -l nodes=1:ppn=16
#PBS -l vmem=100gb
#PBS -l walltime=6:00:00
#PBS -M ouqd@hotmail.com
#PBS -m abe
#PBS -j oe

# This pipeline pbs is produced by the perl script:
# perl MGMP.pl bwa /N/dc2/scratch/xw63/PA2013 PA2013
# Date and time: Thu Jun 21 18:34:58 2018

set +x
module load samtools
module load java
ulimit -s
set -x
cd /N/u/xw63/Carbonate/daphnia/genome_index
mkdir /N/dc2/scratch/xw63/PA2013/Bwa
mkdir /N/dc2/scratch/xw63/PA2013/tmp
set +x
echo ===============================================================
echo 0. making index files, which should be done before submitting pbs
echo ===============================================================

echo ===============================================================
echo 1. After preparing the FASTA file of adapter sequences, trim adapter sequences from sequence reads.
echo ===============================================================

module load java
set -x

set +x
echo ===============================================================
echo 3. Mapping reads to the reference sequence and output bam file.
echo ===============================================================

set -x

	
time ~/bwa-0.7.17/bwa sampe PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/fastq/PA2013-003-R1-paired.fq /N/dc2/scratch/xw63/PA2013/fastq/PA2013-003-R2-paired.fq > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-paired-3.sam &
	
time ~/bwa-0.7.17/bwa samse PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/fastq/PA2013-003-R1-unpaired.fq > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-R1-unpaired-3.sam & 
	
time ~/bwa-0.7.17/bwa samse PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/fastq/PA2013-003-R2-unpaired.fq > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-R2-unpaired-3.sam &

wait 

set +x
echo ===============================================================
echo 4. Combine the SAM files using Picard.
echo ===============================================================

module load java
set -x

time java -XX:ParallelGCThreads=4 -Xmx32g -Xms32g -Djavaio.tmpdir=/N/dc2/scratch/xw63/PA2013/tmp -jar /N/soft/rhel6/picard/2.8.1/picard.jar MergeSamFiles I=/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-paired-3.sam I=/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-R1-unpaired-3.sam I=/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-R2-unpaired-3.sam O=/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-3.sam

set +x
echo ===============================================================
echo 5. Convert the SAM file to the BAM file.
echo ===============================================================

set -x
	
time /N/soft/rhel6/samtools/1.3.1/bin/samtools view -bS /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-3.sam > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-3.bam

set +x
echo ===============================================================
echo =============Task completed.===================
echo ===============================================================
	
